### ISSUE TITLE
Fails with CircuitPython

### ISSUE THREAD

**Issue by tannewt** [adafruit/Adafruit_CircuitPython_TCA9548A#11]
writeto_then_readfrom isn't available on CircuitPython's busio.I2C (yet). This library should do the same detection routine as I2CDevice does.

Found here: https://forums.adafruit.com/viewtopic.php?f=60&t=154454

**Comment by caternuson** [comment]
Thanks. I think this is on me. Will take a look.

Need to keep CP calls to `write_then_readinto` from landing here:
https://github.com/adafruit/Adafruit_CircuitPython_BusDevice/blob/master/adafruit_bus_device/i2c_device.py#L147
Only blinka calls should go down that route.

**Comment by caternuson** [comment]
I'm closing. We can reopen if needed. Hopefully fixed with #12
