### ISSUE TITLE
Add Mock Library to support development outside RPi

### ISSUE THREAD

**Issue by codenio** [adafruit/Adafruit_CircuitPython_TCA9548A#21]
Hi, adding a mock package in this same library, would allow people to develop their code outside RPi

I am currently using the following way to mock adafruit_tca9548a outside RPi, and it works.

```python
try:
    import RPi.GPIO as GPIO
    import adafruit_tca9548a
except:
    import Mock.GPIO as GPIO
    import adafruit_tca9548a.mock as adafruit_tca9548a
```

Thoughts..?

**Comment by ladyada** [comment]
you should be able to use this package outside of raspberry pi, no need to use RPi.GPIO library at all, `blinka` handles just about every single board computer

**Comment by codenio** [comment]
how about ubuntu ?
for development in normal computers where you dont have access to single board computers..

**Comment by ladyada** [comment]
yes blinka works with desktop linux just fine if you have an MCP2221 or FT232H GPIO adapter - you _ could_ make a mock device for when there's no hardware at all but that would go into `blinka`
https://learn.adafruit.com/search?q=blinka

**Comment by codenio** [comment]
in case if is to be added in blinka, then entire RPi needs to be mocked.

FYI, had done this trough [VPi](https://github.com/codenio/virtual-pi),
to support developement when there is no hardware available

**Comment by ladyada** [comment]
that would be a path yes!
