### ISSUE TITLE
Updates examples

### ISSUE THREAD

**Issue by jposada202020** [adafruit/Adafruit_CircuitPython_TCA9548A#34]
New example is desired to show the user how to add two or more sensors

**Comment by caternuson** [comment]
These are sensors that use `BusDevice`?

**Comment by jposada202020** [comment]
Yes indeed.

**Comment by caternuson** [comment]
The current `simpletest` example shows this for two TSL2591s.

**Comment by jposada202020** [comment]
Thanks closing this then 👍🏼

**Comment by caternuson** [comment]
We could still update the example offerings though. Maybe something like this?

- rename current `tca9548a_simpletest.py` to `multi_sensor.py` and that become the example for that
- add a new `tca9548a_simpletest.py` which could be an i2c scan sweep example
- any other use cases that are confusing and an example would help clarify?

**Comment by jposada202020** [comment]
Oh yes I love the idea, will work on that :)

**Comment by caternuson** [comment]
OK, reopened and renamed. I think there was a good scan example in that other issue thread?

**Comment by jposada202020** [comment]
yes there is, I did example for the fakerequests, i was thinking something similar
https://github.com/adafruit/Adafruit_CircuitPython_FakeRequests/blob/main/examples/fakerequests_advancedtest.py
what do you think?

**Comment by caternuson** [comment]
Even simpler, something like:
```python
import board
import adafruit_tca9548a

tca = adafruit_tca9548a.TCA9548A(board.I2C())

for channel in range(8): 
    if tca[channel].try_lock():
        print('Channel {}:'.format(channel), end='')
        tca[channel].scan()
        tca[channel].unlock()
```
Weird - I thought I had dumped something like that over in that PR #32 thread, but not seeing it now. Oh well. Easy enough to rewrite. Output would look something like:
```
Channel 0:[112]
Channel 1:[38, 56, 112]
Channel 2:[112]
Channel 3:[112]
Channel 4:[112]
Channel 5:[94, 112, 119]
Channel 6:[112]
Channel 7:[112]
```

Could maybe make it a little fancier and do a list comp on the return to filter out the TCA's address.

**Comment by jposada202020** [comment]
Will do

**Comment by jerryneedell** [comment]
Can you please output the addresses in Hex?

**Comment by jposada202020** [comment]
yes:) we like hex in the I2C world :)

**Comment by caternuson** [comment]
```python
import board
import adafruit_tca9548a

i2c = board.I2C()

tca = adafruit_tca9548a.TCA9548A(i2c)

for channel in range(8): 
    if tca[channel].try_lock():
        print('Channel {}:'.format(channel), end='')
        addresses = tca[channel].scan()
        print([hex(address) for address in addresses if address != 0x70]) 
        tca[channel].unlock()
 ```

```
Channel 0:[]
Channel 1:['0x26', '0x38']
Channel 2:[]
Channel 3:[]
Channel 4:[]
Channel 5:['0x5e', '0x77']
Channel 6:[]
Channel 7:[]
```
