### ISSUE TITLE
TC library error handling in multiplexer is not available

### ISSUE THREAD

**Issue by ScubaInstructor** [adafruit/Adafruit_CircuitPython_TCA9548A#47]
The issue is probably due to missing documentation:

The below code does work even if 0x70 is not available:
        with board.I2C() as i2c:
            tca = adafruit_tca9548a.TCA9548A(i2c, 0x70)

I only get an error when accessing a channel:
            try:
                shed_AHT20 = adafruit_ahtx0.AHTx0(tca[1])
            except(IOError, RuntimeError, Exception) as error:
              ...

The error is not about 0x70 not available but AHTx0 with 0x38.

After that exception my code blocks. Is there any option to handle the error that 0x70 is not availble?
Did I miss that?

**Comment by ladyada** [comment]
this sounds like a user issue not a library problem. you can try posting to discord or the forums (if you are using adafruit products)
