### ISSUE TITLE
Can I use this lib on jetson tx2?

### ISSUE THREAD

**Issue by Eponeshnikov** [adafruit/Adafruit_CircuitPython_TCA9548A#5]
When I try start example, I have this error NotImplementedError Board not supported.

**Comment by ladyada** [comment]
Hiya Blinka does not have Jetson support quite yet - but once it does then yes this library would just work. Please open up an issue here https://github.com/adafruit/Adafruit_Blinka/issues so you can track it and be notified! we will close this one
